FROM puckel/docker-airflow

USER root

ARG SPARK_VERSION=3.3.1

ARG HADOOP_VERSION=3

RUN apt-get update \
          && mkdir /usr/share/man && mkdir /usr/share/man/man1 \
          && apt install -y openjdk-11-jre-headless scala wget \
          && wget https://archive.apache.org/dist/spark/spark-${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz \
          && tar -xzvf spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz \
          && rm spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz \
          && mv ./spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}/ /opt/spark/ \
          && export JAVA_HOME='/usr/lib/jvm/java-11-openjdk-amd64' \
          && export PATH=$PATH:$JAVA_HOME/bin \
          && export SPARK_HOME='/opt/spark' \
          && export PATH=$PATH:$SPARK_HOME/bin:$SPARK_HOME/sbin \
          && pip install pyspark==${SPARK_VERSION} findspark

EXPOSE 8080 5555 8793

USER airflow
WORKDIR ${AIRFLOW_USER_HOME}
ENTRYPOINT ["/entrypoint.sh"]
CMD ["webserver"]
